// Code generated by generator; DO NOT EDIT.
package query

import (
	"fmt"
	"strconv"
)

// Options represents parsed and validated wttr.in query options.
type Options struct {

	// Output structure format for oneline view (which is always implied when format is used).
	Format string `json:"format,omitempty"`

	// Specify view name
	View string `json:"view,omitempty"`

	// Specify output format
	Output string `json:"output,omitempty"`

	// The name of the user-agent. When specified, overrides the user-agent from the header
	Agent string `json:"agent,omitempty"`

	// Location name the weather is queried about
	Location string `json:"location,omitempty"`

	// Show only current weather
	CurrentOnly bool `json:"current_only,omitempty"`

	// Show current weather and today's forecast
	CurrentPlusToday bool `json:"current_plus_today,omitempty"`

	// Show current weather, today's, and tomorrow's forecast
	CurrentPlusTwoDays bool `json:"current_plus_two_days,omitempty"`

	// Show current weather, forecast for today, tomorrow, and day after
	CurrentPlusThreeDays bool `json:"current_plus_three_days,omitempty"`

	// Force ANSI output format for terminals
	AnsiOutput bool `json:"ansi_output,omitempty"`

	// Restrict output to standard console font glyphs
	StandardFont bool `json:"standard_font,omitempty"`

	// Do not show the 'Follow' line
	NoFollow bool `json:"no_follow,omitempty"`

	// Use metric (SI) units (default everywhere except US) (Overridden by 'uscs' if specified; default is 'uscs' in US)
	Metric bool `json:"metric,omitempty"`

	// Use USCS units (default in the US) (Default is 'uscs' in US, 'metric' elsewhere)
	Uscs bool `json:"uscs,omitempty"`

	// Show wind speed in meters per second
	WindMs bool `json:"wind_ms,omitempty"`

	// Show only day and night forecast (narrow version) (Optimizes output for narrow displays)
	Narrow bool `json:"narrow,omitempty"`

	// Add a frame around the PNG output (Applicable only for PNG output)
	Frame bool `json:"frame,omitempty"`

	// Quiet version, no 'Weather report' text
	Quiet bool `json:"quiet,omitempty"`

	// Superquiet version, no 'Weather report' text or city name
	Superquiet bool `json:"superquiet,omitempty"`

	// Update interval for cyclic location selection
	Period int `json:"period,omitempty"`

	// Random number, used to bypass the first caching layer (alias: dummy, nonce)
	Random int `json:"random,omitempty"`

	// Random number, used to bypass the first caching layer (alias: random, nonce)
	Dummy int `json:"dummy,omitempty"`

	// Random number, used to bypass the first caching layer (alias: dummy, random)
	Nonce int `json:"nonce,omitempty"`

	// Switch off terminal color sequences (no colors)
	NoColor bool `json:"no_color,omitempty"`

	// Specify output language (Languages from 'az' to 'zh' have partial support; others have full support)
	Lang string `json:"lang,omitempty"`

	// Set background color for PNG output in hex (RRGGBB format) (Applicable only for PNG output)
	Background string `json:"background,omitempty"`

	// Force ANSI output mode (Enables ANSI formatting regardless of terminal capabilities)
	ForceAnsi bool `json:"force-ansi,omitempty"`

	// Use dumb terminal mode (Disables advanced terminal features)
	Dumb bool `json:"dumb,omitempty"`

	// Use metric units for measurements (Sets units to metric system; 'M' also enables milliseconds for wind speed)
	UseMetric bool `json:"use_metric,omitempty"`

	// Use milliseconds for wind speed (requires metric units) (Only active when used with 'M' flag for metric units)
	UseMsForWind bool `json:"use_ms_for_wind,omitempty"`

	// Use imperial units for measurements (Sets units to imperial system)
	UseImperial bool `json:"use_imperial,omitempty"`

	// Invert colors in output (Swaps foreground and background colors)
	InvertedColors bool `json:"inverted_colors,omitempty"`

	// Set transparency level for PNG output (Applicable only for PNG output; 255 = not transparent)
	Transparency int `json:"transparency,omitempty"`

	// Disable terminal-specific formatting (Output is not tailored to terminal environment)
	NoTerminal bool `json:"no-terminal,omitempty"`

	// Add padding to output (Adds extra spacing around output content)
	Padding bool `json:"padding,omitempty"`

	// Set the number of forecast days to display (Limits forecast output to the specified number of days)
	Days int `json:"days,omitempty"`

	// Disable captions in output (Removes descriptive text or labels from output)
	NoCaption bool `json:"no-caption,omitempty"`

	// Hide city name in output (Omits location or city name from display)
	NoCity bool `json:"no-city,omitempty"`

	// Disable follow line feature (Prevents automatic line following in output)
	NoFollowLine bool `json:"no-follow-line,omitempty"`

	// Workaround for multiple usage of the question mark in the query
	QuestionMark bool `json:"question_mark,omitempty"`

	// Show debug output
	Debug bool `json:"debug,omitempty"`
}

// ApplyParsedMap populates Options from a validated map[string]string.
// All values are already validated by options.ParseQueryString().
func ApplyParsedMap(opts *Options, raw map[string]string) (*Options, error) {

	// string or fallback
	if v, ok := raw["format"]; ok {
		opts.Format = v
	}

	// string or fallback
	if v, ok := raw["view"]; ok {
		opts.View = v
	}

	// string or fallback
	if v, ok := raw["output"]; ok {
		opts.Output = v
	}

	// string or fallback
	if v, ok := raw["agent"]; ok {
		opts.Agent = v
	}

	// string or fallback
	if v, ok := raw["location"]; ok {
		opts.Location = v
	}

	if v, ok := raw["current_only"]; ok {
		opts.CurrentOnly = (v == "true")
	}

	if v, ok := raw["current_plus_today"]; ok {
		opts.CurrentPlusToday = (v == "true")
	}

	if v, ok := raw["current_plus_two_days"]; ok {
		opts.CurrentPlusTwoDays = (v == "true")
	}

	if v, ok := raw["current_plus_three_days"]; ok {
		opts.CurrentPlusThreeDays = (v == "true")
	}

	if v, ok := raw["ansi_output"]; ok {
		opts.AnsiOutput = (v == "true")
	}

	if v, ok := raw["standard_font"]; ok {
		opts.StandardFont = (v == "true")
	}

	if v, ok := raw["no_follow"]; ok {
		opts.NoFollow = (v == "true")
	}

	if v, ok := raw["metric"]; ok {
		opts.Metric = (v == "true")
	}

	if v, ok := raw["uscs"]; ok {
		opts.Uscs = (v == "true")
	}

	if v, ok := raw["wind_ms"]; ok {
		opts.WindMs = (v == "true")
	}

	if v, ok := raw["narrow"]; ok {
		opts.Narrow = (v == "true")
	}

	if v, ok := raw["frame"]; ok {
		opts.Frame = (v == "true")
	}

	if v, ok := raw["quiet"]; ok {
		opts.Quiet = (v == "true")
	}

	if v, ok := raw["superquiet"]; ok {
		opts.Superquiet = (v == "true")
	}

	if v, ok := raw["period"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for period: %w", err)
		}
		opts.Period = n
	}

	if v, ok := raw["random"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for random: %w", err)
		}
		opts.Random = n
	}

	if v, ok := raw["dummy"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for dummy: %w", err)
		}
		opts.Dummy = n
	}

	if v, ok := raw["nonce"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for nonce: %w", err)
		}
		opts.Nonce = n
	}

	if v, ok := raw["no_color"]; ok {
		opts.NoColor = (v == "true")
	}

	// string or fallback
	if v, ok := raw["lang"]; ok {
		opts.Lang = v
	}

	// string or fallback
	if v, ok := raw["background"]; ok {
		opts.Background = v
	}

	if v, ok := raw["force-ansi"]; ok {
		opts.ForceAnsi = (v == "true")
	}

	if v, ok := raw["dumb"]; ok {
		opts.Dumb = (v == "true")
	}

	if v, ok := raw["use_metric"]; ok {
		opts.UseMetric = (v == "true")
	}

	if v, ok := raw["use_ms_for_wind"]; ok {
		opts.UseMsForWind = (v == "true")
	}

	if v, ok := raw["use_imperial"]; ok {
		opts.UseImperial = (v == "true")
	}

	if v, ok := raw["inverted_colors"]; ok {
		opts.InvertedColors = (v == "true")
	}

	if v, ok := raw["transparency"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for transparency: %w", err)
		}
		opts.Transparency = n
	}

	if v, ok := raw["no-terminal"]; ok {
		opts.NoTerminal = (v == "true")
	}

	if v, ok := raw["padding"]; ok {
		opts.Padding = (v == "true")
	}

	if v, ok := raw["days"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for days: %w", err)
		}
		opts.Days = n
	}

	if v, ok := raw["no-caption"]; ok {
		opts.NoCaption = (v == "true")
	}

	if v, ok := raw["no-city"]; ok {
		opts.NoCity = (v == "true")
	}

	if v, ok := raw["no-follow-line"]; ok {
		opts.NoFollowLine = (v == "true")
	}

	if v, ok := raw["question_mark"]; ok {
		opts.QuestionMark = (v == "true")
	}

	if v, ok := raw["debug"]; ok {
		opts.Debug = (v == "true")
	}

	// Optional: apply defaults for unset fields (if not zero-value)

	// if default is true
	if !opts.Metric {
		opts.Metric = true
	}

	if opts.Lang == "" {
		opts.Lang = "en"
	}

	// force to string for template
	if opts.Transparency == 0 {
		opts.Transparency = 150
	}

	return opts, nil
}
