// Code generated by generator; DO NOT EDIT.
package config

// Options represents the configuration options for weather queries.
type Options struct {
	
	// Show only current weather
	CurrentOnly bool `json:"current_only"`
	
	// Show current weather and today's forecast
	CurrentPlusToday bool `json:"current_plus_today"`
	
	// Show current weather, today's, and tomorrow's forecast
	CurrentPlusTwoDays bool `json:"current_plus_two_days"`
	
	// Show current weather, forecast for today, tomorrow, and day after
	CurrentPlusThreeDays bool `json:"current_plus_three_days"`
	
	// Force ANSI output format for terminals
	AnsiOutput bool `json:"ansi_output"`
	
	// Restrict output to standard console font glyphs
	StandardFont bool `json:"standard_font"`
	
	// Do not show the 'Follow' line
	NoFollow bool `json:"no_follow"`
	
	// Use metric (SI) units (default everywhere except US) (Overridden by 'uscs' if specified; default is 'uscs' in US)
	Metric bool `json:"metric"`
	
	// Use USCS units (default in the US) (Default is 'uscs' in US, 'metric' elsewhere)
	Uscs bool `json:"uscs"`
	
	// Show wind speed in meters per second
	WindMs bool `json:"wind_ms"`
	
	// Show only day and night forecast (narrow version)
	Narrow bool `json:"narrow"`
	
	// Add a frame around the PNG output (Applicable only for PNG output)
	Frame bool `json:"frame"`
	
	// Quiet version, no 'Weather report' text
	Quiet bool `json:"quiet"`
	
	// Superquiet version, no 'Weather report' text or city name
	Superquiet bool `json:"superquiet"`
	
	// Update interval for cyclic location selection
	Period int `json:"period"`
	
	// Random number, used to bypass the first caching layer (alias: dummy, nonce)
	Random int `json:"random"`
	
	// Random number, used to bypass the first caching layer (alias: random, nonce)
	Dummy int `json:"dummy"`
	
	// Random number, used to bypass the first caching layer (alias: dummy, random)
	Nonce int `json:"nonce"`
	
	// Switch off terminal color sequences (no colors)
	NoColor bool `json:"no_color"`
	
	// Specify output language (Languages from 'az' to 'zh' have partial support; others have full support)
	Lang string `json:"lang"`
	
	// Set background color for PNG output in hex (RRGGBB format) (Applicable only for PNG output)
	Background string `json:"background"`
	
	// Specify output format for one-line weather info (Used for status bars in tools like tmux)
	Format string `json:"format"`
	
	// Force ANSI output mode (Enables ANSI formatting regardless of terminal capabilities)
	ForceAnsi bool `json:"force-ansi"`
	
	// Use dumb terminal mode (Disables advanced terminal features)
	Dumb bool `json:"dumb"`
	
	// Use narrow layout for output (Optimizes output for narrow displays)
	Narrow bool `json:"narrow"`
	
	// Use metric units for measurements (Sets units to metric system; 'M' also enables milliseconds for wind speed)
	UseMetric bool `json:"use_metric"`
	
	// Use milliseconds for wind speed (requires metric units) (Only active when used with 'M' flag for metric units)
	UseMsForWind bool `json:"use_ms_for_wind"`
	
	// Use imperial units for measurements (Sets units to imperial system)
	UseImperial bool `json:"use_imperial"`
	
	// Invert colors in output (Swaps foreground and background colors)
	InvertedColors bool `json:"inverted_colors"`
	
	// Set transparency level for PNG output (Applicable only for PNG output; 255 = not transparent)
	Transparency int `json:"transparency"`
	
	// Disable terminal-specific formatting (Output is not tailored to terminal environment)
	NoTerminal bool `json:"no-terminal"`
	
	// Add padding to output (Adds extra spacing around output content)
	Padding bool `json:"padding"`
	
	// Set the number of forecast days to display (Limits forecast output to the specified number of days)
	Days int `json:"days"`
	
	// Disable captions in output (Removes descriptive text or labels from output)
	NoCaption bool `json:"no-caption"`
	
	// Hide city name in output (Omits location or city name from display)
	NoCity bool `json:"no-city"`
	
	// Disable follow line feature (Prevents automatic line following in output)
	NoFollowLine bool `json:"no-follow-line"`
	
	// Workaround for multiple usage of the question mark in the query
	QuestionMark bool `json:"question_mark"`
	
}
