// Package generate creates query.Options struct + mapping logic from YAML spec.
package generate

import (
	"fmt"
	"os"
	"text/template"
	"unicode"

	"gopkg.in/yaml.v3"
)

var (
	configFile = "spec/options/options.yaml"
	outputFile = "internal/query/options.go"

	tmplSrc = `// Code generated by generator; DO NOT EDIT.
package query

import (
	"fmt"
	"strconv"
)

// Options represents parsed and validated wttr.in query options.
type Options struct {
{{range .QueryOptions}}
	// {{.Description}}{{if .Note}} ({{.Note}}){{end}}
	{{.FieldName}} {{.FieldType}} ` + "`json:\"{{.Name}},omitempty\"`" + `
{{end}}
}

// ApplyParsedMap populates Options from a validated map[string]string.
// All values are already validated by options.ParseQueryString().
func ApplyParsedMap(raw map[string]string) (*Options, error) {
	opts := &Options{}

{{range .QueryOptions}}
	{{if eq .FieldType "bool"}}
	if v, ok := raw["{{.Name}}"]; ok {
		opts.{{.FieldName}} = (v == "true")
	}
	{{else if eq .FieldType "int"}}
	if v, ok := raw["{{.Name}}"]; ok {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("invalid integer for {{.Name}}: %w", err)
		}
		opts.{{.FieldName}} = n
	}
	{{else}} // string or fallback
	if v, ok := raw["{{.Name}}"]; ok {
		opts.{{.FieldName}} = v
	}
	{{end}}
{{end}}

	// Optional: apply defaults for unset fields (if not zero-value)
{{range .QueryOptions}}
	{{if .Default}}
		{{if eq .FieldType "bool"}}
			{{if .Default}}  // if default is true
	if !opts.{{.FieldName}} { opts.{{.FieldName}} = true }
			{{else}}
	if !opts.{{.FieldName}} { opts.{{.FieldName}} = false }  // redundant but safe
			{{end}}
		{{else if eq .FieldType "int"}}
			{{ $def := printf "%v" .Default }}  // force to string for template
	if opts.{{.FieldName}} == 0 { opts.{{.FieldName}} = {{ $def }} }
		{{else if eq .FieldType "string"}}
	if opts.{{.FieldName}} == "" { opts.{{.FieldName}} = "{{ printf "%v" .Default }}" }
		{{end}}
	{{end}}
{{end}}

	return opts, nil
}
`
)

// OptionConfig mirrors the YAML structure (adjusted for generation needs)
type OptionConfig struct {
	Name        string            `yaml:"name"`
	Short       string            `yaml:"short,omitempty"`
	Description string            `yaml:"description"`
	Type        string            `yaml:"type"`
	Default     interface{}       `yaml:"default"`
	Active      bool              `yaml:"active"`
	Note        string            `yaml:"note,omitempty"`
	Values      []string          `yaml:"values,omitempty"` // simplified
	ValuesMap   map[string]string `yaml:"values_map,omitempty"`
	Range       struct {
		Min interface{} `yaml:"min"`
		Max interface{} `yaml:"max"`
	} `yaml:"range,omitempty"`
	Validate []string `yaml:"validate,omitempty"`
}

// OptionsConfig is the root of the YAML
type OptionsConfig struct {
	QueryOptions     []OptionConfig    `yaml:"query_options"`
	FormatSpecifiers []FormatSpecifier `yaml:"format_specifiers"`
}

type FormatSpecifier struct {
	Specifier   string `yaml:"specifier"`
	Description string `yaml:"description"`
	Active      bool   `yaml:"active"`
	Note        string `yaml:"note,omitempty"`
}

// GeneratedField holds template data for one field
type GeneratedField struct {
	Name        string
	FieldName   string
	Description string
	FieldType   string
	Note        string
	Default     interface{}
}

// toGoType maps YAML type → Go type
func toGoType(typ string) string {
	switch typ {
	case "boolean":
		return "bool"
	case "integer":
		return "int"
	case "string":
		return "string"
	default:
		return "string" // fallback – be conservative
	}
}

// toFieldName turns kebab/snake-case → PascalCase
func toFieldName(name string) string {
	if name == "" {
		return ""
	}
	var result []rune
	upperNext := true
	for _, r := range name {
		if r == '-' || r == '_' {
			upperNext = true
			continue
		}
		if upperNext {
			result = append(result, unicode.ToUpper(r))
			upperNext = false
		} else {
			result = append(result, r)
		}
	}
	return string(result)
}

// GenerateOptionsAndParser is the main entry point
func GenerateOptionsAndParser() error {
	data, err := os.ReadFile(configFile)
	if err != nil {
		return fmt.Errorf("read config: %w", err)
	}

	var cfg OptionsConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return fmt.Errorf("unmarshal yaml: %w", err)
	}

	var fields []GeneratedField
	for _, opt := range cfg.QueryOptions {
		if !opt.Active {
			continue
		}
		fields = append(fields, GeneratedField{
			Name:        opt.Name,
			FieldName:   toFieldName(opt.Name),
			Description: opt.Description,
			FieldType:   toGoType(opt.Type),
			Note:        opt.Note,
			Default:     opt.Default,
		})
	}

	tmpl, err := template.New("query_options").Parse(tmplSrc)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, struct {
		QueryOptions []GeneratedField
	}{
		QueryOptions: fields,
	})
}
