package generate

import (
	"io/ioutil"
	"os"
	"text/template"
	"unicode"

	"gopkg.in/yaml.v2"
)

var (
	configFile  = "spec/options/options.yaml"
	outputFile  = "internal/query/options.go"
	optionsTmpl = `// Code generated by generator; DO NOT EDIT.
package query

// Options represents the configuration options for weather queries.
type Options struct {
	{{range .QueryOptions}}
	// {{.Description}}{{if .Note}} ({{.Note}}){{end}}
	{{.FieldName}} {{.FieldType}} ` + "`json:\"{{.Name}}\"`" + `
	{{end}}
}
`
)

// OptionConfig represents a single option from the YAML config.
type OptionConfig struct {
	Name        string            `yaml:"name"`
	Short       string            `yaml:"short,omitempty"`
	Description string            `yaml:"description"`
	Type        string            `yaml:"type"`
	Default     interface{}       `yaml:"default"`
	Active      bool              `yaml:"active"`
	Note        string            `yaml:"note,omitempty"`
	Values      []interface{}     `yaml:"values,omitempty"`
	ValuesMap   map[string]string `yaml:"values_map,omitempty"`
	Range       struct {
		Min interface{} `yaml:"min"`
		Max interface{} `yaml:"max"`
	} `yaml:"range,omitempty"`
	Validate []string `yaml:"validate,omitempty"`
}

// FormatSpecifier represents a format specifier from the YAML config.
type FormatSpecifier struct {
	Specifier   string `yaml:"specifier"`
	Description string `yaml:"description"`
	Active      bool   `yaml:"active"`
	Note        string `yaml:"note,omitempty"`
}

// OptionsConfig represents the full YAML configuration structure.
type OptionsConfig struct {
	QueryOptions     []OptionConfig    `yaml:"query_options"`
	FormatSpecifiers []FormatSpecifier `yaml:"format_specifiers"`
}

// GeneratedOption represents the data used for template rendering.
type GeneratedOption struct {
	Name        string
	FieldName   string
	Description string
	FieldType   string
	Note        string
}

// toGoType converts YAML type to Go type.
func toGoType(yamlType string) string {
	switch yamlType {
	case "boolean":
		return "bool"
	case "integer":
		return "int"
	case "string":
		return "string"
	default:
		return "interface{}"
	}
}

// toFieldName converts option name to Go field name (camelCase to PascalCase).
func toFieldName(name string) string {
	if name == "" {
		return ""
	}
	runes := []rune(name)
	result := make([]rune, 0, len(runes))
	shouldCapitalize := true
	for _, r := range runes {
		if r == '_' || r == '-' {
			shouldCapitalize = true
			continue
		}
		if shouldCapitalize {
			result = append(result, unicode.ToUpper(r))
			shouldCapitalize = false
		} else {
			result = append(result, r)
		}
	}
	return string(result)
}

// GenerateOptions generates the Options struct based on the YAML config.
func GenerateOptions() error {
	// Read YAML config file
	data, err := ioutil.ReadFile(configFile)
	if err != nil {
		return err
	}

	// Unmarshal YAML into OptionsConfig
	var config OptionsConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return err
	}

	// Prepare data for template
	var generatedOptions []GeneratedOption
	for _, opt := range config.QueryOptions {
		if !opt.Active {
			continue
		}
		generatedOptions = append(generatedOptions, GeneratedOption{
			Name:        opt.Name,
			FieldName:   toFieldName(opt.Name),
			Description: opt.Description,
			FieldType:   toGoType(opt.Type),
			Note:        opt.Note,
		})
	}

	// Parse template
	tmpl, err := template.New("options").Parse(optionsTmpl)
	if err != nil {
		return err
	}

	// Create output file
	out, err := os.Create(outputFile)
	if err != nil {
		return err
	}
	defer out.Close()

	// Execute template and write to file
	return tmpl.Execute(out, struct {
		QueryOptions []GeneratedOption
	}{
		QueryOptions: generatedOptions,
	})
}
